FROM wso2/wso2am:4.7.0

ADD --chown=wso2carbon:wso2 \
  https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.28/mysql-connector-java-8.0.28.jar \
  /home/wso2carbon/wso2am-4.7.0/repository/components/lib/
  